/*
 * JS for Account generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function Account_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'Account_mobilebutton_11',
        'mobileimage_12': 'Account_mobileimage_12',
        'mobileworkarea_10': 'Account_mobileworkarea_10',
        'mobiletextinput_25': 'Account_mobiletextinput_25',
        'mobiletextinput_26': 'Account_mobiletextinput_26',
        'mobileselectmenu_30': 'Account_mobileselectmenu_30',
        'mobileselectmenu_30-0': 'Account_mobileselectmenu_30-0',
        'mobilebutton_33': 'Account_mobilebutton_33',
        'mobilelist_3': 'Account_mobilelist_3',
        'mobilelistitem_4': 'Account_mobilelistitem_4',
        'mobilelistitembutton_5': 'Account_mobilelistitembutton_5',
        'liHelp': 'Account_liHelp',
        'mobilelistitembutton_7': 'Account_mobilelistitembutton_7',
        'panelAboutOTARC': 'Account_panelAboutOTARC',
        'mobilelistitembutton_9': 'Account_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Account';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Account_onLoad = function() {
            Account_elementsExtraJS();

            Account_deviceEvents();
            Account_windowEvents();
            Account_elementsEvents();
        };

    // screen window events


    function Account_windowEvents() {

        $('#Account').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Account_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Account_elementsExtraJS() {
        // screen (Account) extra code

        /* mobileselectmenu_30 */

        $("#Account_mobileselectmenu_30").parent().find("a.ui-btn").attr("tabindex", "10");

        /* mobilelist_3 */

        listView = $("#Account_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Account_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function Account_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Account_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Account_panel_menu"]').panel("open");

                }
            },
        }, '#Account_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#Account_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Account_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#Account_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#Account_panel_menu [name="liHelp"]');

        $(document).off("click", '#Account_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#Account_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#Account").on("pagebeforeshow", "#Account", function(event, ui) {
        Apperyio.CurrentScreen = "Account";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Account_onLoad();
};

$(document).off("pagecreate", "#Account").on("pagecreate", "#Account", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Account_js();
});