/*
 * JS for Child generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function Child_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'Child_mobilebutton_11',
        'mobileimage_12': 'Child_mobileimage_12',
        'mobileworkarea_10': 'Child_mobileworkarea_10',
        'mobilelabel_39': 'Child_mobilelabel_39',
        'fldCDFname': 'Child_fldCDFname',
        'spacer_48': 'Child_spacer_48',
        'rgCDGender': 'Child_rgCDGender',
        'rbBoyChild': 'Child_rbBoyChild',
        'rbGirlChild': 'Child_rbGirlChild',
        'spacer_47': 'Child_spacer_47',
        'mobilelabel_46': 'Child_mobilelabel_46',
        'fldCDBirthdate': 'Child_fldCDBirthdate',
        'spacer_42': 'Child_spacer_42',
        'btnCDStart': 'Child_btnCDStart',
        'mobilelist_3': 'Child_mobilelist_3',
        'mobilelistitem_4': 'Child_mobilelistitem_4',
        'mobilelistitembutton_5': 'Child_mobilelistitembutton_5',
        'liHelp': 'Child_liHelp',
        'mobilelistitembutton_7': 'Child_mobilelistitembutton_7',
        'panelAboutOTARC': 'Child_panelAboutOTARC',
        'mobilelistitembutton_9': 'Child_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Child';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Child_onLoad = function() {
            Child_elementsExtraJS();

            Child_deviceEvents();
            Child_windowEvents();
            Child_elementsEvents();
        };

    // screen window events


    function Child_windowEvents() {

        $('#Child').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Child_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Child_elementsExtraJS() {
        // screen (Child) extra code

        /* fldCDBirthdate */

        Child_fldCDBirthdate_selector = "#Child_fldCDBirthdate";
        Child_fldCDBirthdate_dataPickerOptions = {
            dateFormat: "dd/mm/yy",
            firstDay: 0,

            maxDate: new Date(""),

            minDate: new Date(""),

            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };

        Child_fldCDBirthdate_dataPickerOptions.defaultDate = new Date("01/01/2014");

        Apperyio.__registerComponent('fldCDBirthdate', new Apperyio.ApperyMobileDatePickerComponent("Child_fldCDBirthdate", Child_fldCDBirthdate_dataPickerOptions));

        /* mobilelist_3 */

        listView = $("#Child_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Child_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function Child_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Child_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Child_panel_menu"]').panel("open");

                }
            },
        }, '#Child_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("change", '#Child_mobilecontainer1 [name="rgCDGender"]').on({
            change: function(event) {
                try {
                    $a.storage["varGender"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('rgCDGender', this), 'get', 'selectedOption'))
                } catch (e) {
                    console.error(e)
                };
            },
        }, '#Child_mobilecontainer1 [name="rgCDGender"]');
        $(document).off("click", '#Child_mobilecontainer1 [name="rbBoyChild"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varGender"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('rbBoyChild', this), 'get', 'value'))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#Child_mobilecontainer1 [name="rbBoyChild"]');
        $(document).off("click", '#Child_mobilecontainer1 [name="rbGirlChild"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varGender"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('rbGirlChild', this), 'get', 'value'))
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#Child_mobilecontainer1 [name="rbGirlChild"]');

        $(document).off("click", '#Child_mobilecontainer1 [name="btnCDStart"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varName"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('fldCDFname', this), 'get', 'text'))
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["age"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('fldCDBirthdate', this), 'get', 'defaultDateValue'))
                    } catch (e) {
                        console.error(e)
                    };
                    var age = localStorage.getItem('age');

                    var dt1 = parseInt(age.substring(0, 2));
                    var mon1 = parseInt(age.substring(3, 5));
                    var yr1 = parseInt(age.substring(6, 10));
                    var date1 = new Date(yr1, mon1 - 1, dt1);

                    var today = new Date();
                    var theage = today.getFullYear() - yr1;

                    if (today.getMonth() < date1.getMonth() || (today.getMonth() == date1.getMonth() && today.getDate() < date1.getDate())) {
                        theage--;
                    }

                    localStorage.setItem('theage', theage);;
                    try {
                        $a.storage["varD"].update("$", $a.c15r($a.UIHandler.resolveGeneratedComponent('fldCDBirthdate', this), 'get', 'defaultDateValue'))
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('Preflight', {
                        reverse: false
                    });

                }
            },
        }, '#Child_mobilecontainer1 [name="btnCDStart"]');

        $(document).off("click", '#Child_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Child_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#Child_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#Child_panel_menu [name="liHelp"]');

        $(document).off("click", '#Child_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#Child_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#Child").on("pagebeforeshow", "#Child", function(event, ui) {
        Apperyio.CurrentScreen = "Child";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Child_onLoad();
};

$(document).off("pagecreate", "#Child").on("pagecreate", "#Child", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Child_js();
});