/*
 * JS for EyeContactV1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function EyeContactV1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'EyeContactV1_mobilebutton_11',
        'mobileimage_12': 'EyeContactV1_mobileimage_12',
        'mobileworkarea_10': 'EyeContactV1_mobileworkarea_10',
        'mobilelabel_23': 'EyeContactV1_mobilelabel_23',
        'mobileradiogroup_29': 'EyeContactV1_mobileradiogroup_29',
        'rECYes': 'EyeContactV1_rECYes',
        'rECNo': 'EyeContactV1_rECNo',
        'vimeo_28': 'EyeContactV1_vimeo_28',
        'btnECNext': 'EyeContactV1_btnECNext',
        'mobilelist_3': 'EyeContactV1_mobilelist_3',
        'mobilelistitem_4': 'EyeContactV1_mobilelistitem_4',
        'mobilelistitembutton_5': 'EyeContactV1_mobilelistitembutton_5',
        'liHelp': 'EyeContactV1_liHelp',
        'mobilelistitembutton_7': 'EyeContactV1_mobilelistitembutton_7',
        'panelAboutOTARC': 'EyeContactV1_panelAboutOTARC',
        'mobilelistitembutton_9': 'EyeContactV1_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'EyeContactV1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var EyeContactV1_onLoad = function() {
            EyeContactV1_elementsExtraJS();

            EyeContactV1_deviceEvents();
            EyeContactV1_windowEvents();
            EyeContactV1_elementsEvents();
        };

    // screen window events


    function EyeContactV1_windowEvents() {

        $('#EyeContactV1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function EyeContactV1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function EyeContactV1_elementsExtraJS() {
        // screen (EyeContactV1) extra code

        VimeoPlayer(Apperyio("vimeo_28"));

        /* mobilelist_3 */

        listView = $("#EyeContactV1_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#EyeContactV1_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function EyeContactV1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#EyeContactV1_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="EyeContactV1_panel_menu"]').panel("open");

                }
            },
        }, '#EyeContactV1_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#EyeContactV1_mobilecontainer1 [name="rECYes"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varEyeContact"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#EyeContactV1_mobilecontainer1 [name="rECYes"]');
        $(document).off("click", '#EyeContactV1_mobilecontainer1 [name="rECNo"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varEyeContact"].update("$", "1")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#EyeContactV1_mobilecontainer1 [name="rECNo"]');

        $(document).off("click", '#EyeContactV1_mobilecontainer1 [name="btnECNext"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('FollowsPointV1', {
                        reverse: false
                    });

                }
            },
        }, '#EyeContactV1_mobilecontainer1 [name="btnECNext"]');

        $(document).off("click", '#EyeContactV1_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#EyeContactV1_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#EyeContactV1_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#EyeContactV1_panel_menu [name="liHelp"]');

        $(document).off("click", '#EyeContactV1_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#EyeContactV1_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#EyeContactV1").on("pagebeforeshow", "#EyeContactV1", function(event, ui) {
        Apperyio.CurrentScreen = "EyeContactV1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    EyeContactV1_onLoad();
};

$(document).off("pagecreate", "#EyeContactV1").on("pagecreate", "#EyeContactV1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    EyeContactV1_js();
});