/*
 * JS for Functions generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function Functions_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'Functions_mobilebutton_11',
        'mobileimage_12': 'Functions_mobileimage_12',
        'mobileworkarea_10': 'Functions_mobileworkarea_10',
        'mobilelist_12': 'Functions_mobilelist_12',
        'mobilelistitem_13': 'Functions_mobilelistitem_13',
        'mobilelistitembutton_14': 'Functions_mobilelistitembutton_14',
        'mobilelistitem_15': 'Functions_mobilelistitem_15',
        'mobilelistitembutton_16': 'Functions_mobilelistitembutton_16',
        'mobilelistitem_17': 'Functions_mobilelistitem_17',
        'mobilelistitembutton_18': 'Functions_mobilelistitembutton_18',
        'mobilelistitem_19': 'Functions_mobilelistitem_19',
        'mobilelistitembutton_20': 'Functions_mobilelistitembutton_20',
        'mobilelist_3': 'Functions_mobilelist_3',
        'mobilelistitem_4': 'Functions_mobilelistitem_4',
        'mobilelistitembutton_5': 'Functions_mobilelistitembutton_5',
        'liHelp': 'Functions_liHelp',
        'mobilelistitembutton_7': 'Functions_mobilelistitembutton_7',
        'panelAboutOTARC': 'Functions_panelAboutOTARC',
        'mobilelistitembutton_9': 'Functions_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Functions';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Functions_onLoad = function() {
            Functions_elementsExtraJS();

            Functions_deviceEvents();
            Functions_windowEvents();
            Functions_elementsEvents();
        };

    // screen window events


    function Functions_windowEvents() {

        $('#Functions').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Functions_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Functions_elementsExtraJS() {
        // screen (Functions) extra code

        /* mobilelist_12 */

        listView = $("#Functions_mobilelist_12");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Functions_mobilelist_12 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_13 */

        /* mobilelistitem_15 */

        /* mobilelistitem_17 */

        /* mobilelistitem_19 */

        /* mobilelist_3 */

        listView = $("#Functions_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Functions_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function Functions_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Functions_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Functions_panel_menu"]').panel("open");

                }
            },
        }, '#Functions_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#Functions_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Functions_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#Functions_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#Functions_panel_menu [name="liHelp"]');

        $(document).off("click", '#Functions_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#Functions_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#Functions").on("pagebeforeshow", "#Functions", function(event, ui) {
        Apperyio.CurrentScreen = "Functions";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Functions_onLoad();
};

$(document).off("pagecreate", "#Functions").on("pagecreate", "#Functions", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Functions_js();
});