/*
 * JS for Home generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function Home_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'Home_mobilebutton_11',
        'mobileimage_12': 'Home_mobileimage_12',
        'mobileworkarea_10': 'Home_mobileworkarea_10',
        'mobilelabel_12': 'Home_mobilelabel_12',
        'mobilelabel_13': 'Home_mobilelabel_13',
        'vimeo_15': 'Home_vimeo_15',
        'btnHomeStart': 'Home_btnHomeStart',
        'mobilelist_3': 'Home_mobilelist_3',
        'mobilelistitem_4': 'Home_mobilelistitem_4',
        'mobilelistitembutton_5': 'Home_mobilelistitembutton_5',
        'liHelp': 'Home_liHelp',
        'mobilelistitembutton_7': 'Home_mobilelistitembutton_7',
        'panelAboutOTARC': 'Home_panelAboutOTARC',
        'mobilelistitembutton_9': 'Home_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Home';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Home_onLoad = function() {
            Home_elementsExtraJS();

            Home_deviceEvents();
            Home_windowEvents();
            Home_elementsEvents();
        };

    // screen window events


    function Home_windowEvents() {

        $('#Home').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Home_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Home_elementsExtraJS() {
        // screen (Home) extra code

        VimeoPlayer(Apperyio("vimeo_15"));

        /* mobilelist_3 */

        listView = $("#Home_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Home_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function Home_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Home_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Home_panel_menu"]').panel("open");

                }
            },
        }, '#Home_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#Home_mobilecontainer1 [name="btnHomeStart"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Child', {
                        reverse: false
                    });

                }
            },
        }, '#Home_mobilecontainer1 [name="btnHomeStart"]');

        $(document).off("click", '#Home_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Home_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#Home_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#Home_panel_menu [name="liHelp"]');

        $(document).off("click", '#Home_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#Home_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#Home").on("pagebeforeshow", "#Home", function(event, ui) {
        Apperyio.CurrentScreen = "Home";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Home_onLoad();
};

$(document).off("pagecreate", "#Home").on("pagecreate", "#Home", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Home_js();
});