/*
 * JS for Preflight generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function Preflight_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'Preflight_mobilebutton_11',
        'mobileimage_12': 'Preflight_mobileimage_12',
        'mobileworkarea_10': 'Preflight_mobileworkarea_10',
        'mobilelabel_12': 'Preflight_mobilelabel_12',
        'spacer_13': 'Preflight_spacer_13',
        'lblName': 'Preflight_lblName',
        'btnPFStart': 'Preflight_btnPFStart',
        'spacer_14': 'Preflight_spacer_14',
        'mobilelist_3': 'Preflight_mobilelist_3',
        'mobilelistitem_4': 'Preflight_mobilelistitem_4',
        'mobilelistitembutton_5': 'Preflight_mobilelistitembutton_5',
        'liHelp': 'Preflight_liHelp',
        'mobilelistitembutton_7': 'Preflight_mobilelistitembutton_7',
        'panelAboutOTARC': 'Preflight_panelAboutOTARC',
        'mobilelistitembutton_9': 'Preflight_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'Preflight';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var Preflight_onLoad = function() {
            Preflight_elementsExtraJS();

            var theage = localStorage.getItem('theage');
            var varName = localStorage.getItem('varName');

            Appery('lblName').text('Running diagnosis for ' + varName + ', age ' + theage + ' years');

            ;

            Preflight_deviceEvents();
            Preflight_windowEvents();
            Preflight_elementsEvents();
        };

    // screen window events


    function Preflight_windowEvents() {

        $('#Preflight').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function Preflight_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function Preflight_elementsExtraJS() {
        // screen (Preflight) extra code

        /* mobilelist_3 */

        listView = $("#Preflight_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#Preflight_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function Preflight_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#Preflight_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="Preflight_panel_menu"]').panel("open");

                }
            },
        }, '#Preflight_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#Preflight_mobilecontainer1 [name="btnPFStart"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varEyeContact"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["varPointing"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["varWBB"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["varImitation"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };
                    try {
                        $a.storage["varResponse2Name"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };
                    Apperyio.navigateTo('EyeContactV1', {
                        reverse: false
                    });
                    try {
                        $a.storage["varX"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#Preflight_mobilecontainer1 [name="btnPFStart"]');

        $(document).off("click", '#Preflight_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#Preflight_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#Preflight_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#Preflight_panel_menu [name="liHelp"]');

        $(document).off("click", '#Preflight_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#Preflight_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#Preflight").on("pagebeforeshow", "#Preflight", function(event, ui) {
        Apperyio.CurrentScreen = "Preflight";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    Preflight_onLoad();
};

$(document).off("pagecreate", "#Preflight").on("pagecreate", "#Preflight", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Preflight_js();
});