/*
 * JS for ResultsSummaryV1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function ResultsSummaryV1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'ResultsSummaryV1_mobilebutton_11',
        'mobileimage_12': 'ResultsSummaryV1_mobileimage_12',
        'mobileworkarea_10': 'ResultsSummaryV1_mobileworkarea_10',
        'lblProcessed': 'ResultsSummaryV1_lblProcessed',
        'spacer_27': 'ResultsSummaryV1_spacer_27',
        'imgNotAtRisk': 'ResultsSummaryV1_imgNotAtRisk',
        'imgAtRisk': 'ResultsSummaryV1_imgAtRisk',
        'lblAssessment': 'ResultsSummaryV1_lblAssessment',
        'spacer_29': 'ResultsSummaryV1_spacer_29',
        'lblEmail': 'ResultsSummaryV1_lblEmail',
        'lblResults': 'ResultsSummaryV1_lblResults',
        'mobilelist_3': 'ResultsSummaryV1_mobilelist_3',
        'mobilelistitem_4': 'ResultsSummaryV1_mobilelistitem_4',
        'mobilelistitembutton_5': 'ResultsSummaryV1_mobilelistitembutton_5',
        'liHelp': 'ResultsSummaryV1_liHelp',
        'mobilelistitembutton_7': 'ResultsSummaryV1_mobilelistitembutton_7',
        'panelAboutOTARC': 'ResultsSummaryV1_panelAboutOTARC',
        'mobilelistitembutton_9': 'ResultsSummaryV1_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.mappings["ResultsSummaryV1_restservice1_onsuccess_mapping_0"] = {
        "homeScreen": "ResultsSummaryV1",
        "directions": [

        {
            "from_name": "restservice1",
            "from_type": "SERVICE_RESPONSE",

            "to_name": "varX",
            "to_type": "LOCAL_STORAGE",

            "mappings": [

            {

                "source": "$['body']['count']",
                "target": "$"

            }

            ]
        }

        ]
    };

    Apperyio.mappings["ResultsSummaryV1_restservice1_onbeforesend_mapping_0"] = {
        "homeScreen": "ResultsSummaryV1",
        "directions": [

        {
            "from_name": "varEyeContact",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['ec']"

            }

            ]
        },

        {
            "from_name": "varFollowsPoint",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['fp']"

            }

            ]
        },

        {
            "from_name": "varPointing",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['p']"

            }

            ]
        },

        {
            "from_name": "varImitation",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['im']"

            }

            ]
        },

        {
            "from_name": "varResponse2Name",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['r2n']"

            }

            ]
        },

        {
            "from_name": "varWBB",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['wbb']"

            }

            ]
        },

        {
            "from_name": "varName",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['child']"

            }

            ]
        },

        {
            "from_name": "varD",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['dob']"

            }

            ]
        },

        {
            "from_name": "varGender",
            "from_type": "LOCAL_STORAGE",

            "to_name": "restservice1",
            "to_type": "SERVICE_REQUEST",

            "to_default": {
                "headers": {
                    "Authorization": "{salesforce_access_token}",
                    "Content-Type": "application/json"
                },
                "parameters": {},
                "body": {
                    "child": "XXXXXX",
                    "ec": 7,
                    "fp": 9,
                    "p": 1,
                    "im": 1,
                    "r2n": 1,
                    "wbb": 1,
                    "dob": "01/01/1970",
                    "gender": "Boy"
                }
            },

            "mappings": [

            {

                "source": "$",
                "target": "$['body']['gender']"

            }

            ]
        }

        ]
    };

    Apperyio.datasources = Apperyio.datasources || {};

    window.restservice1 = Apperyio.datasources.restservice1 = new Apperyio.DataSource(Salesforce_ASDetectResultsRESTCreate, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["ResultsSummaryV1_restservice1_onbeforesend_mapping_0"]);
            try {
                $a.c15r("lblProcessed", "set", "text", 'Processing...')
            } catch (e) {
                console.error(e)
            };
        },
        "onComplete": function(jqXHR, textStatus) {
            try {
                $a.c15r("lblResults", "set", "text", $a.storage["varX"].get("$"))
            } catch (e) {
                console.error(e)
            };
            var t = parseInt(localStorage.getItem('varX'));

            if (t > 4) {

                Apperyio('imgAtRisk').show();
                Appery('lblAssessment').text("This child is considered At Risk.");

            } else {

                Apperyio('imgNotAtRisk').show();
                Appery('lblAssessment').text("This child is considered Not At Risk.");
            }

            Apperyio('lblEmail').show();
            Appery('lblProcessed').text("Thankyou, your results have been processed.");

            ;

            Apperyio.refreshScreenFormElements("ResultsSummaryV1");
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["ResultsSummaryV1_restservice1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {
            try {
                $a.c15r("lblResults", "set", "text", 'ERROR')
            } catch (e) {
                console.error(e)
            };
        }
    });

    Apperyio.CurrentScreen = 'ResultsSummaryV1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var ResultsSummaryV1_onLoad = function() {
            ResultsSummaryV1_elementsExtraJS();

            try {
                restservice1.execute({});
            } catch (e) {
                console.error(e);
                hideSpinner();
            };

            ResultsSummaryV1_deviceEvents();
            ResultsSummaryV1_windowEvents();
            ResultsSummaryV1_elementsEvents();
        };

    // screen window events


    function ResultsSummaryV1_windowEvents() {

        $('#ResultsSummaryV1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function ResultsSummaryV1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function ResultsSummaryV1_elementsExtraJS() {
        // screen (ResultsSummaryV1) extra code

        /* mobilelist_3 */

        listView = $("#ResultsSummaryV1_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#ResultsSummaryV1_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function ResultsSummaryV1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#ResultsSummaryV1_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="ResultsSummaryV1_panel_menu"]').panel("open");

                }
            },
        }, '#ResultsSummaryV1_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#ResultsSummaryV1_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#ResultsSummaryV1_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#ResultsSummaryV1_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#ResultsSummaryV1_panel_menu [name="liHelp"]');

        $(document).off("click", '#ResultsSummaryV1_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#ResultsSummaryV1_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#ResultsSummaryV1").on("pagebeforeshow", "#ResultsSummaryV1", function(event, ui) {
        Apperyio.CurrentScreen = "ResultsSummaryV1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    ResultsSummaryV1_onLoad();
};

$(document).off("pagecreate", "#ResultsSummaryV1").on("pagecreate", "#ResultsSummaryV1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    ResultsSummaryV1_js();
});