/*
 * JS for SummaryV1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function SummaryV1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'SummaryV1_mobilebutton_11',
        'mobileimage_12': 'SummaryV1_mobileimage_12',
        'mobileworkarea_10': 'SummaryV1_mobileworkarea_10',
        'lblAtRisk': 'SummaryV1_lblAtRisk',
        'spacer_12': 'SummaryV1_spacer_12',
        'btnSummary': 'SummaryV1_btnSummary',
        'mobilelist_3': 'SummaryV1_mobilelist_3',
        'mobilelistitem_4': 'SummaryV1_mobilelistitem_4',
        'mobilelistitembutton_5': 'SummaryV1_mobilelistitembutton_5',
        'liHelp': 'SummaryV1_liHelp',
        'mobilelistitembutton_7': 'SummaryV1_mobilelistitembutton_7',
        'panelAboutOTARC': 'SummaryV1_panelAboutOTARC',
        'mobilelistitembutton_9': 'SummaryV1_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'SummaryV1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var SummaryV1_onLoad = function() {
            SummaryV1_elementsExtraJS();

            //var eyeContact = parseInt(localStorage.getItem('varEyeContact'));
            //var followsPoint= parseInt(localStorage.getItem('varFollowsPoint'));
            //var imitation= parseInt(localStorage.getItem('varImitation'));
            //var response2Name = parseInt(localStorage.getItem('varResponse2Name'));
            //var pointing=parseInt(localStorage.getItem('varPointing'));
            //var wbb = parseInt(localStorage.getItem('varWBB'));
            //var total = eyeContact + followsPoint + pointing + wbb + response2Name + imitation;

            //localStorage.setItem('totalScore', total);
            //var myvar  = localStorage.getItem('myVar');
            //if (total > 3) {
            //Appery('lblRisk').text("Total score: "+total+". This child is considered At Risk.");    
            //} else {
            // Appery('lblRisk').text("Total score: "+total+". This child is considered Not At Risk.");  
            //}

            ;

            SummaryV1_deviceEvents();
            SummaryV1_windowEvents();
            SummaryV1_elementsEvents();
        };

    // screen window events


    function SummaryV1_windowEvents() {

        $('#SummaryV1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function SummaryV1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function SummaryV1_elementsExtraJS() {
        // screen (SummaryV1) extra code

        /* mobilelist_3 */

        listView = $("#SummaryV1_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#SummaryV1_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function SummaryV1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#SummaryV1_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="SummaryV1_panel_menu"]').panel("open");

                }
            },
        }, '#SummaryV1_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#SummaryV1_mobilecontainer1 [name="btnSummary"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ResultsSummaryV1', {
                        reverse: false
                    });

                }
            },
        }, '#SummaryV1_mobilecontainer1 [name="btnSummary"]');

        $(document).off("click", '#SummaryV1_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#SummaryV1_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#SummaryV1_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#SummaryV1_panel_menu [name="liHelp"]');

        $(document).off("click", '#SummaryV1_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#SummaryV1_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#SummaryV1").on("pagebeforeshow", "#SummaryV1", function(event, ui) {
        Apperyio.CurrentScreen = "SummaryV1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    SummaryV1_onLoad();
};

$(document).off("pagecreate", "#SummaryV1").on("pagecreate", "#SummaryV1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    SummaryV1_js();
});