/*
 * JS for WavingByeByeV1 generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'cf359b4d-9919-41ac-84f0-4ec73508f392';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Response2NameV1",
    "location": "Response2NameV1.html"
}, {
    "name": "SummaryV1",
    "location": "SummaryV1.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}, {
    "name": "ImitationV1",
    "location": "ImitationV1.html"
}, {
    "name": "FollowsPointV1",
    "location": "FollowsPointV1.html"
}, {
    "name": "Pointing",
    "location": "Pointing.html"
}, {
    "name": "WavingByeByeV1",
    "location": "WavingByeByeV1.html"
}, {
    "name": "Account",
    "location": "Account.html"
}, {
    "name": "Child",
    "location": "Child.html"
}, {
    "name": "AboutOTARC",
    "location": "AboutOTARC.html"
}, {
    "name": "PointingV1",
    "location": "PointingV1.html"
}, {
    "name": "Help",
    "location": "Help.html"
}, {
    "name": "ResponseToName",
    "location": "ResponseToName.html"
}, {
    "name": "Home",
    "location": "Home.html"
}, {
    "name": "Functions",
    "location": "Functions.html"
}, {
    "name": "Imitation",
    "location": "Imitation.html"
}, {
    "name": "WavingByeBye",
    "location": "WavingByeBye.html"
}, {
    "name": "ResultsSummaryV1",
    "location": "ResultsSummaryV1.html"
}, {
    "name": "SocialSmilesV1",
    "location": "SocialSmilesV1.html"
}, {
    "name": "EyeContactV1",
    "location": "EyeContactV1.html"
}, {
    "name": "Preflight",
    "location": "Preflight.html"
}];

function WavingByeByeV1_js() {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_11': 'WavingByeByeV1_mobilebutton_11',
        'mobileimage_12': 'WavingByeByeV1_mobileimage_12',
        'mobileworkarea_10': 'WavingByeByeV1_mobileworkarea_10',
        'mobilelabel_12': 'WavingByeByeV1_mobilelabel_12',
        'mobileradiogroup_13': 'WavingByeByeV1_mobileradiogroup_13',
        'rWBBYes': 'WavingByeByeV1_rWBBYes',
        'rWBBNo': 'WavingByeByeV1_rWBBNo',
        'vimeo_17': 'WavingByeByeV1_vimeo_17',
        'btnWBBNext': 'WavingByeByeV1_btnWBBNext',
        'mobilelist_3': 'WavingByeByeV1_mobilelist_3',
        'mobilelistitem_4': 'WavingByeByeV1_mobilelistitem_4',
        'mobilelistitembutton_5': 'WavingByeByeV1_mobilelistitembutton_5',
        'liHelp': 'WavingByeByeV1_liHelp',
        'mobilelistitembutton_7': 'WavingByeByeV1_mobilelistitembutton_7',
        'panelAboutOTARC': 'WavingByeByeV1_panelAboutOTARC',
        'mobilelistitembutton_9': 'WavingByeByeV1_mobilelistitembutton_9'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    /*
     * Nonvisual components
     */

    Apperyio.mappings = Apperyio.mappings || {};

    Apperyio.datasources = Apperyio.datasources || {};

    Apperyio.CurrentScreen = 'WavingByeByeV1';
    _.chain(Apperyio.mappings).filter(function(m) {
        return m.homeScreen === Apperyio.CurrentScreen;
    }).each(Apperyio.UIHandler.hideTemplateComponents);

    /*
     * Events and handlers
     */

    // On Load
    var WavingByeByeV1_onLoad = function() {
            WavingByeByeV1_elementsExtraJS();

            WavingByeByeV1_deviceEvents();
            WavingByeByeV1_windowEvents();
            WavingByeByeV1_elementsEvents();
        };

    // screen window events


    function WavingByeByeV1_windowEvents() {

        $('#WavingByeByeV1').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    };

    // device events


    function WavingByeByeV1_deviceEvents() {
        document.addEventListener("deviceready", function() {

        });
    };

    // screen elements extra js


    function WavingByeByeV1_elementsExtraJS() {
        // screen (WavingByeByeV1) extra code

        VimeoPlayer(Apperyio("vimeo_17"));

        /* mobilelist_3 */

        listView = $("#WavingByeByeV1_mobilelist_3");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#WavingByeByeV1_mobilelist_3 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_4 */

        /* liHelp */

        /* panelAboutOTARC */

    };

    // screen elements handler


    function WavingByeByeV1_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });

        $(document).off("click", '#WavingByeByeV1_mobileheader1 [name="mobilebutton_11"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    $('[id="WavingByeByeV1_panel_menu"]').panel("open");

                }
            },
        }, '#WavingByeByeV1_mobileheader1 [name="mobilebutton_11"]');

        $(document).off("click", '#WavingByeByeV1_mobilecontainer1 [name="rWBBYes"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varWBB"].update("$", "0")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#WavingByeByeV1_mobilecontainer1 [name="rWBBYes"]');
        $(document).off("click", '#WavingByeByeV1_mobilecontainer1 [name="rWBBNo"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        $a.storage["varWBB"].update("$", "1")
                    } catch (e) {
                        console.error(e)
                    };

                }
            },
        }, '#WavingByeByeV1_mobilecontainer1 [name="rWBBNo"]');

        $(document).off("click", '#WavingByeByeV1_mobilecontainer1 [name="btnWBBNext"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('ImitationV1', {
                        reverse: false
                    });

                }
            },
        }, '#WavingByeByeV1_mobilecontainer1 [name="btnWBBNext"]');

        $(document).off("click", '#WavingByeByeV1_panel_menu [name="mobilelistitem_4"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Home', {
                        reverse: false
                    });

                }
            },
        }, '#WavingByeByeV1_panel_menu [name="mobilelistitem_4"]');

        $(document).off("click", '#WavingByeByeV1_panel_menu [name="liHelp"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('Help', {
                        reverse: false
                    });

                }
            },
        }, '#WavingByeByeV1_panel_menu [name="liHelp"]');

        $(document).off("click", '#WavingByeByeV1_panel_menu [name="panelAboutOTARC"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('AboutOTARC', {
                        reverse: false
                    });

                }
            },
        }, '#WavingByeByeV1_panel_menu [name="panelAboutOTARC"]');

    };

    $(document).off("pagebeforeshow", "#WavingByeByeV1").on("pagebeforeshow", "#WavingByeByeV1", function(event, ui) {
        Apperyio.CurrentScreen = "WavingByeByeV1";
        _.chain(Apperyio.mappings).filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        }).each(Apperyio.UIHandler.hideTemplateComponents);
    });

    WavingByeByeV1_onLoad();
};

$(document).off("pagecreate", "#WavingByeByeV1").on("pagecreate", "#WavingByeByeV1", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    WavingByeByeV1_js();
});